# Generated by Django 2.0 on 2017-12-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('prepared', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliquotQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliquotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('datetime', models.DateTimeField()),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rationale', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('technician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.DateTimeField()),
                ('equipment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage', models.CharField(blank=True, max_length=255, null=True)),
                ('aliquot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assay_aliquot', to='api.Aliquot')),
            ],
        ),
        migrations.CreateModel(
            name='AssayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_assay', to='api.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interpretation_assay', to='api.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('obtained', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SequencingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('fileservice_uuid', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('md5', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencingfile_assay', to='api.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('external_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_sample_type', to='api.SampleType'),
        ),
        migrations.AddField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_subject', to='api.Subject'),
        ),
        migrations.AddField(
            model_name='assay',
            name='assay_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assay_assay_status', to='api.AssayStatus'),
        ),
        migrations.AddField(
            model_name='assay',
            name='assay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assay_assay_type', to='api.AssayType'),
        ),
        migrations.AddField(
            model_name='assay',
            name='reanalysis_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assay_reanalysis_id', to='api.Assay'),
        ),
        migrations.AddField(
            model_name='assay',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assay_sample', to='api.Sample'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='aliquot_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquot_aliquot_quality', to='api.AliquotQuality'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='aliquot_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquot_aliquot_type', to='api.AliquotType'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquot_sample', to='api.Sample'),
        ),
    ]
