# Generated by Django 2.0 on 2018-01-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180105_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='aliquot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assay_aliquot', to='api.Aliquot'),
        ),
    ]
