# Generated by Django 2.0 on 2018-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180108_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
